ARG RUBY_VERSION
FROM ruby:$RUBY_VERSION

RUN apk add --no-cache --update build-base \
  bash \
  git \
  postgresql-dev \
  nodejs \
  && rm -rf /var/cache/apk/*

RUN mkdir -p /app
WORKDIR /app

COPY Gemfile Gemfile.lock ./

RUN gem update --system
RUN bundle install -j $(nproc)

# Configure the main process to run when running the image
CMD ["rails", "server", "-b", "0.0.0.0"]
